In [1]:
import tensorflow as tf
import numpy as np
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

y_xor = np.array([[0], [1], [1], [0]])
y_or = np.array([[0], [1], [1], [1]])
y_and = np.array([[0], [0], [0], [1]])

In [5]:
model =  tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(2,)))

model.add(tf.keras.layers.Dense(4,activation='relu'))
model.add(tf.keras.layers.Dense(3,activation='relu'))



model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
              loss='binary_crossentropy',
              metrics=['binary_accuracy'])

history = model.fit(x, y_xor, batch_size=4, epochs=500, verbose=1)


###accuracy = #predicciones correctas/ #total




Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 0.7652 - binary_accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7526 - binary_accuracy: 0.7500
Epoch 3/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7406 - binary_accuracy: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7291 - binary_accuracy: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 12ms/step - loss: 0.7182 - binary_accuracy: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7079 - binary_accuracy: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6981 - binary_accuracy: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6889 - binary_accuracy: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6819 - binary_accuracy: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 9ms/

2.8.2


In [ ]:


import tensorflow as tf # Our main TensorFlow import
import timeit
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
#from google.colab import drive
#drive.mount('/content/drive')
print(tf.__version__)

2.8.2


In [ ]:
def eager_function(x):
  result = 2*x**2 + 3*x + 5
  print(result)
  return result

In [ ]:
x = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])

In [ ]:
print("Eager time:", timeit.timeit(lambda: eager_function(x), number=10))

tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
tf.Tensor([10. 19. 32. 49. 70.], shape=(5,), dtype=float32)
Eager time: 0.016983503999995264


In [ ]:
graph_function = tf.function(eager_function)

In [ ]:
print("Graph time:", timeit.timeit(lambda: graph_function(x), number=10))

Tensor("add_1:0", shape=(5,), dtype=float32)
Graph time: 0.023475700000005872
